Repository prgrms-web-devcourse-final-project/WEB6_8_MOCI_BE, pull requests merged in 2025-09, with the labels that each got.

#18 [feat]: file upload Entity 생성
  src/main/java/com/moci_3d_backend/domain/fileUpload/entity/FileUpload.java
Labels: feat

#20 [feat] 채팅 엔티티 생성
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/entity/MentorChatMessage.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/entity/MentorChatRoom.java
Labels: feat

#21 [feat] : AI채팅방 엔티티 생성, AI 메시지 엔티티 생성 #1
  src/main/java/com/moci_3d_backend/domain/chat/ai/MessageStatus.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/SenderType.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatMessage/entity/AiChatMessage.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatRoom/entity/AiChatRoom.java
Labels: feat

#23 [feat] : 유저 엔티티 작성
  src/main/java/com/moci_3d_backend/domain/User/entity/User.java
Labels: feat

#22 Feat#17: 공개자료실 관련 DTO생성 및 entity 자료형 수정
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveCreateRequest.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveListResponse.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveResponse.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveUpdateRequest.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/entity/PublicArchive.java
  src/main/java/com/moci_3d_backend/domain/fileUpload/entity/FileUpload.java
  src/main/java/com/moci_3d_backend/domain/user/entity/User.java
Labels: feat

#27 [feat] : 유저 엔티티 작성
  src/main/java/com/moci_3d_backend/domain/User/entity/User.java
Labels: feat

#28 [feat] file upload dto 생성
  src/main/java/com/moci_3d_backend/domain/fileUpload/dto/FileUploadDto.java
Labels: feat

#32 [fix#31] : Entity 매핑 오류 수정
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/entity/PublicArchive.java
Labels: bug, fix

#37 [feat] : 멘티의 멘토 채팅방 CRUD 중 CRD 구현 (#33)
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/controller/ApiV1MenteeChatRoomController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/dto/MentorChatRoomResponse.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/entity/MentorChatRoom.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/repository/MentorChatRoomRepository.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MentorChatRoomDtoService.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MentorChatRoomService.java
Labels: feat

#40 [feat]: fileupload service,repository,controller 생성
  src/main/java/com/moci_3d_backend/domain/fileUpload/controller/FileUploadController.java
  src/main/java/com/moci_3d_backend/domain/fileUpload/entity/FileUpload.java
  src/main/java/com/moci_3d_backend/domain/fileUpload/repository/FileUploadRepository.java
  src/main/java/com/moci_3d_backend/domain/fileUpload/service/FileUploadService.java
  src/test/java/com/moci_3d_backend/domain/fileUpload/FileUploadControllerTest.java
Labels: feat

#46 [Fix]: file upload test 수정 및 pr양식 수정
  .github/PULL_REQUEST_TEMPLATE.md
  db_dev.trace.db
  src/main/java/com/moci_3d_backend/global/security/SecurityConfig.java
  src/test/java/com/moci_3d_backend/domain/fileUpload/FileUploadControllerTest.java
Labels: fix

#44 Feat#39: PublicArchiveController 생성
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/controller/PublicArchiveController.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/service/PublicArchiveService.java
Labels: feat

#49 [feat#47]: 요청 게시판 Entity생성
  src/main/java/com/moci_3d_backend/domain/archive/archive_request/entity/ArchiveRequest.java
Labels: feat

#67 [feat] User Login 기능 구현
  src/main/java/com/moci_3d_backend/domain/user/controller/AuthController.java
  src/main/java/com/moci_3d_backend/domain/user/controller/UserController.java
  src/main/java/com/moci_3d_backend/domain/user/dto/request/UserLoginRequest.java
  src/main/java/com/moci_3d_backend/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/com/moci_3d_backend/domain/user/dto/response/UserResponse.java
  src/main/java/com/moci_3d_backend/domain/user/entity/User.java
  src/main/java/com/moci_3d_backend/domain/user/repository/UserRepository.java
  src/main/java/com/moci_3d_backend/domain/user/service/UserService.java
Labels: feat

#68 [refactor] AI채팅방 읽음처리 리팩토링 #1
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatMessage/controller/AiChatMessageController.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatMessage/repository/AiChatMessageRepository.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatMessage/service/AiChatMessageService.java
Labels: refactor

#71 [feat] 멘토채팅방 구현#59
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/entity/MentorChatMessage.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/controller/ApiV1MenteeChatRoomController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/controller/ApiV1MentorChatRoomController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/dto/CreateMentorChatRoom.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/dto/DetailMentorChatRoom.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/dto/MentorChatRoomResponse.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/entity/MentorChatRoom.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/repository/MentorChatRoomRepository.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MenteeChatRoomService.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MentorChatRoomDtoService.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MentorChatRoomService.java
  src/main/java/com/moci_3d_backend/global/webSocket/readme.md
Labels: feat

#75 [feat] : AI 채팅방, 메시지 추가 API기능 구현#1
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatMessage/controller/AiChatMessageController.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatMessage/repository/AiChatMessageRepository.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatMessage/service/AiChatMessageService.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatRoom/controller/AiChatRoomController.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatRoom/entity/AiChatRoom.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatRoom/repository/AiChatRoomRepository.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatRoom/service/AiChatRoomService.java
Labels: feat

#79 [feat] Querydsl 도입 #72
  build.gradle
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/entity/MentorChatMessage.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/controller/ApiV1MenteeChatRoomController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/dto/MentorChatRoomResponse.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/repository/MentorChatRoomRepository.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/repository/MentorChatRoomRepositoryCustom.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/repository/MentorChatRoomRepositoryImpl.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MenteeChatRoomService.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MentorChatRoomService.java
  src/main/java/com/moci_3d_backend/global/jpa/querydsl/QueryDslConfig.java
  src/main/java/com/moci_3d_backend/global/jpa/querydsl/readme.md
  src/main/resources/application.yml
Labels: feat

#85 Refactor#80 : 교육,요청 리팩터링 및 임시 권한 체크 추가
  src/main/java/com/moci_3d_backend/domain/archive/archive_request/controller/ArchiveRequestController.java
  src/main/java/com/moci_3d_backend/domain/archive/archive_request/repository/ArchiveRequestRepository.java
  src/main/java/com/moci_3d_backend/domain/archive/archive_request/service/ArchiveRequestService.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/controller/PublicArchiveController.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveCreateRequest.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveResponse.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveUpdateRequest.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/entity/ArchiveCategory.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/entity/PublicArchive.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/mapper/PublicArchiveMapper.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/service/PublicArchiveService.java
  src/main/java/com/moci_3d_backend/global/initData/DevInitData.java
Labels: feat, refactor

#94 [feat] : #93 멘토 전체 채팅방 조회
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/controller/ApiV1MentorChatRoomController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/repository/MentorChatRoomRepository.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MentorChatRoomService.java
Labels: feat

#96 Feat#86 : 검색(QueryDsl 및 Komoran형태소 분석기 추가) 및 프론트 요청 반영 등
  build.gradle
  src/main/java/com/moci_3d_backend/domain/archive/archive_request/service/ArchiveRequestService.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/controller/PublicArchiveController.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveListItemDto.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveListResponse.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveResponse.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveUserDto.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/mapper/PublicArchiveMapper.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/repository/PublicArchiveRepository.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/repository/PublicArchiveRepositoryCustom.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/repository/PublicArchiveRepositoryImpl.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/service/PublicArchiveService.java
  src/main/java/com/moci_3d_backend/global/initData/DevInitData.java
  src/main/java/com/moci_3d_backend/global/util/KoreanTextAnalyzer.java
Labels: feat

#100 [feat#99] 파일 업로드 관련 수정
  src/main/java/com/moci_3d_backend/domain/fileUpload/controller/FileUploadController.java
  src/main/java/com/moci_3d_backend/domain/fileUpload/service/FileUploadService.java
Labels: feat

#102 [feat#88-partial] feat#88 분할 (Rq 추가 , PW 암호화 initData 적용)
  src/main/java/com/moci_3d_backend/domain/user/controller/AuthController.java
  src/main/java/com/moci_3d_backend/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/com/moci_3d_backend/domain/user/dto/response/UserCreateTokenResponse.java
  src/main/java/com/moci_3d_backend/domain/user/dto/response/UserResponse.java
  src/main/java/com/moci_3d_backend/domain/user/entity/User.java
  src/main/java/com/moci_3d_backend/global/initData/DevInitData.java
  src/main/java/com/moci_3d_backend/global/rq/Rq.java
  tatus
Labels: feat

#110 [feat] : #95 채팅에 인증 추가
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/controller/ApiV1ChatMessageController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/controller/ApiV1ChatMessageRestController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/dto/ChatReceiveMessage.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/dto/ChatSendMessage.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/controller/ApiV1MenteeChatRoomController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/controller/ApiV1MentorChatRoomController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/dto/CreateMentorChatRoom.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/entity/MentorChatRoom.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MenteeChatRoomService.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MentorChatRoomService.java
  src/main/java/com/moci_3d_backend/global/initData/DevInitData.java
  src/main/java/com/moci_3d_backend/global/security/JwtHandshakeInterceptor.java
  src/main/java/com/moci_3d_backend/global/security/SecurityUser.java
  src/main/java/com/moci_3d_backend/global/security/StompJwtInterceptor.java
Labels: feat

#117 [feat] : #112 멘토 채팅방 테스트 케이스 생성
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/dto/DetailMentorChatRoom.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/dto/MentorChatRoomResponse.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/entity/MentorChatRoom.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/repository/MentorChatRoomRepositoryImpl.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MentorChatRoomService.java
  src/main/java/com/moci_3d_backend/global/initData/DevInitData.java
  src/test/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/controller/ApiV1MenteeChatRoomControllerTest.java
  src/test/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/controller/ApiV1MentorChatRoomControllerTest.java
Labels: feat

#127 Feat#124 교육자료실 프론트 요구사항 반영(필터링)
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/controller/PublicArchiveController.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/dto/PublicArchiveListItemDto.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/mapper/PublicArchiveMapper.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/repository/PublicArchiveRepository.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/repository/PublicArchiveRepositoryCustom.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/repository/PublicArchiveRepositoryImpl.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/service/PublicArchiveService.java
Labels: feat

#131 [feat] : 채팅저장 기능 연결 및 테스트 케이스 추가
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/controller/ApiV1ChatMessageController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/service/MentorChatMessageService.java
  src/test/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/controller/ApiV1ChatMessageRestControllerTest.java
Labels: feat
