Repository prgrms-web-devcourse-final-project/WEB6_8_MOCI_BE, pull requests merged in 2025-10, with the labels that each got.

#140 feat#130 : Digital_LEVEL 분할 완료
  src/main/java/com/moci_3d_backend/domain/user/controller/AuthController.java
  src/main/java/com/moci_3d_backend/domain/user/controller/UserController.java
  src/main/java/com/moci_3d_backend/domain/user/dto/request/UserDigitalLevelRequest.java
  src/main/java/com/moci_3d_backend/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/com/moci_3d_backend/domain/user/dto/response/UserCreateTokenResponse.java
  src/main/java/com/moci_3d_backend/domain/user/dto/response/UserDigitalLevelResponse.java
  src/main/java/com/moci_3d_backend/domain/user/dto/response/UserRegisterResponse.java
  src/main/java/com/moci_3d_backend/domain/user/entity/User.java
  src/main/java/com/moci_3d_backend/domain/user/service/UserService.java
  src/main/java/com/moci_3d_backend/global/initData/DevInitData.java
Labels: feat

#138 [Fix] 파일 업로드 미리보기
  src/main/java/com/moci_3d_backend/config/WebSocketConfig.java
  src/main/java/com/moci_3d_backend/global/config/WebConfig.java
  src/main/java/com/moci_3d_backend/global/security/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/static/test-webrtc.html
Labels: fix

#143 [fix] : swagger 설명 수정
  src/main/java/com/moci_3d_backend/domain/archive/archive_request/controller/ArchiveRequestController.java
  src/main/java/com/moci_3d_backend/domain/archive/public_archive/controller/PublicArchiveController.java
Labels: documentation, fix

#146 Feat#142 : User 마이페이지 기능 구현
  src/main/java/com/moci_3d_backend/domain/user/controller/AuthController.java
  src/main/java/com/moci_3d_backend/domain/user/controller/UserController.java
  src/main/java/com/moci_3d_backend/domain/user/dto/request/UserEmailUpdateRequest.java
  src/main/java/com/moci_3d_backend/domain/user/dto/request/UserLoginRequest.java
  src/main/java/com/moci_3d_backend/domain/user/dto/request/UserPasswordUpdateRequest.java
  src/main/java/com/moci_3d_backend/domain/user/dto/request/UserRegisterRequest.java
  src/main/java/com/moci_3d_backend/domain/user/dto/response/UserRegisterResponse.java
  src/main/java/com/moci_3d_backend/domain/user/dto/response/UserWithdrawResponse.java
  src/main/java/com/moci_3d_backend/domain/user/service/UserService.java
Labels: feat

#147 [feat] RoleHierarchy 적용
  src/main/java/com/moci_3d_backend/domain/archive/archive_request/controller/ArchiveRequestController.java
  src/main/java/com/moci_3d_backend/global/security/SecurityConfig.java
Labels: feat

#151 fix150 : 전화번호 중복검사 시 로그인 인증 요청 삭제
  src/main/java/com/moci_3d_backend/global/security/CustomAuthenticationFilter.java
  src/main/java/com/moci_3d_backend/global/security/SecurityConfig.java
Labels: fix

#153 Chore#152 : CORS url 설정
  src/main/java/com/moci_3d_backend/global/security/SecurityConfig.java
  terraform/outputs.tf
  terraform/s3.tf
Labels: chore

#155 [fix] : #154 채팅방 FE 요구 반영
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/controller/ApiV1ChatMessageController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/dto/ChatReceiveMessage.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/dto/ChatSendMessage.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/service/MentorChatMessageDtoService.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatMessage/service/MentorChatMessageService.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/controller/ApiV1MenteeChatRoomController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/controller/ApiV1MentorChatRoomController.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/dto/MentorChatRoomResponse.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/entity/MentorChatRoom.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/repository/MentorChatRoomRepositoryImpl.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MentorChatRoomService.java
Labels: fix

#159 Fix#156 deploy.yml
  .github/workflows/deploy.yml
Labels: fix

#163 Fix#156 deploy수정
  .github/workflows/deploy.yml
Labels: fix

#172 [fix] : #171 부주의했던 코드 수정
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/repository/MentorChatRoomRepository.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MenteeChatRoomService.java
  src/main/java/com/moci_3d_backend/domain/chat/mentor/mentorChatRoom/service/MentorChatRoomService.java
Labels: fix

#173 [feat] AI 메세지 응답 (스트리밍)#1
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatMessage/controller/AiChatMessageController.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatMessage/controller/AiChatStreamController.java
  src/main/java/com/moci_3d_backend/domain/chat/ai/aiChatMessage/service/AiChatMessageService.java
  src/main/java/com/moci_3d_backend/external/ai/client/GeminiClient.java
  src/main/java/com/moci_3d_backend/global/config/WebClientConfig.java
  src/main/java/com/moci_3d_backend/global/security/SecurityConfig.java
  src/main/java/com/moci_3d_backend/global/springDoc/SpringDocConfig.java
  src/main/resources/application.yml
Labels: feat
